### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by nabilzhafri** [dortania/Anti-Hackintosh-Buyers-Guide#2]
I clicked on "Understanding and fixing "Couldn't allocate runtime area" errors" under Memory Maps and Protections, but seems like the link is invalid.

**Comment by khronokernel** [comment]
Oh the link has KASLR misspelled, just fixed it: https://github.com/dortania/Anti-Hackintosh-Buyers-Guide/commit/9bc002b2a755ec21357ed353b11e7aa7a665bb85
Thanks for point that out
